name: Helm Release
on:
  push:
    - main
  paths:
    - 'opensource/argocd/**'
    - '!**md'
  jobs:
    get-chart:
      runs-on: ubuntu-latest
      name: 'Get modified charts'
      outputs:
        chart: ${{ steps.get-chart.outputs.chart }}
      steps:
        - uses: actions/checkout@v3
        - id: get-chart
          name: 'Get modified charts'
          run: |
            files_changed="$(git show --pretty="" --name-only)"
            charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "opensource/[^/]*/[^/]*" | sort | uniq || true)"
            if [[ "$num_charts_changed" -eq "1" ]]; then
              chart_name=$(echo "$charts_dirs_changed" | sed "s|opensource/||g")
              echo "chart=${chart_name}" >> $GITHUB_OUTPUT
            fi
    update-index:
      runs-on: ubuntu-latest
      need: get-chart
      name: Update charts index
      steps:
        - uses: actions/checkout@v3
          with:
            path: helm-source
            fetch-depth: 1
        - uses: actions/checkout@v3
          with:
            path: helm-repo
            fetch-depth: 1
        - id: helm release
          name: 'helm release'
          run: |
            helm package helm-source/opensource/${{ steps.get-chart.outputs.result }} -u -d helm-repo/

