name: Helm Release
on:
  push:
    paths:
      - 'opensource/**/**'
      - '!**md'
    branches:
      - main
jobs:
  helm-release:
    runs-on: ubuntu-latest
    name: Update charts index
    steps:
      - name: checkout helm resource
        uses: actions/checkout@v3
        with:
          path: helm-source
          fetch-depth: 1
      - name: checkout helm repo
        uses: actions/checkout@v3
        with:
          path: helm-repo
          ref: gh-pages
          fetch-depth: 1
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Helm Package
        working-directory: helm-source
        run: |
          for charts in opensource/*/ ; do
            for chart_name in "$charts"*; do
              helm package $chart_name -u -d ../helm-repo/
            done
          done
      - name: Upload helm chart
        working-directory: helm-repo
        run: |
          helm repo index . --url https://evopss.github.io/charts
          git config user.name 'ender viggin'
          git config user.email 'ender.viggin.coder@gmail.com'
          git add .
          git commit -m "upload helm chart"
          git push

