name: Helm Release
on:
  push:
    paths:
      - 'opensource/**/**'
      - '!**md'
    branches:
      - main
  jobs:
    helm-release:
      runs-on: ubuntu-latest
      name: Update charts index
      steps:
        - uses: actions/checkout@v3
          with:
            path: helm-source
            fetch-depth: 1
        - uses: actions/checkout@v3
          with:
            path: helm-repo
            fetch-depth: 1
        - id: helm release
          name: 'helm release'
          run: |
            files_changed="$(git show --pretty="" --name-only)"
            charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "opensource/[^/]*/[^/]*" | sort | uniq || true)"
            for chart_name in $charts_dirs_changed; do
              helm package helm-source/$opensource/ -u -d helm-repo/
            done
            ls helm-repo/

